### ISSUE TITLE
Is it compatible PHP 5.6 ?

### ISSUE THREAD

**Issue by anolek** [genesis-global/salesforce#1]
Hi,

Is your package compatible PHP 5.6 ?
I would like to use it, but there are "string" type in one classe and one interface.

> GenesisGlobal\Salesforce\Client\SalesforceClient 
> GenesisGlobal\Salesforce\Client\SalesforceClientInterface

Thanks

**Comment by coderaf** [comment]
Hey it was compatible, but we changed in the mean time. But i will add new branch/realese for php 5.6 tomorrow if you need it.

**Comment by anolek** [comment]
Thanks for your answer,

Don't worry i will upgrade to PHP 7.
If i asked this question, it is because there is no "php require" line in your composer.json.

If it's only for PHP >= 7.0, could you add this line in your composer.json please ? :) (Or i can send a PR)
```
"require": {
     // ....
     "php": "^7.0"
```

**Comment by coderaf** [comment]
sorry i had no time yesterday, but today i downgraded code to php 5.6 cause one of our apps, actually need one with such version.

**Comment by anolek** [comment]
Don't worry ! Thanks ! ;)
